name: Metrics
on:
  schedule: [{cron: "0 */5 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: josephistired/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: josephistired
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: America/New_York
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: html
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_pwa: yes
          plugin_pagespeed_url: https://josephcarmosino.com/
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_repositories: yes
          plugin_repositories_featured: DiscordBot-v14, Discord-Pi-hole-Bot, Discord-SelfBot, Auto-Lurk
          plugin_repositories_order: featured, pinned, starred, random
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
